#!/bin/bash

#SBATCH -t 0-12:00
#SBATCH -p priority
#SBATCH -c 1
#SBATCH --mem=4G
#SBATCH -o BL_ESCOTT_%j.out
#SBATCH -e BL_ESCOTT_%j.err
#SBATCH -J BL_ESCOTT
#SBATCH --account=marks

# modified to run on Singularity on O2

# scoring_ESCOTT_substitutions.sh
#
# Description:
# This script runs the ESCOTT prediction in a Docker container. It ensures that all necessary
# dependencies are available and sets up the environment for running the ESCOTT prediction.
# The script mounts the required directories into the Docker container, executes the prediction,
# and saves the output files.
#
# Prerequisites:
# - Docker must be installed on the host machine.
# - The user must have permission to run Docker commands.
# - The Docker image for ESCOTT with all dependencies must be pulled from Docker Hub using the following command:
#   docker pull tekpinar/prescott-docker:v1.6.0
#
# Note:
# The generated prediction files in the Docker container will have root ownership. After the execution,
# change the ownership of the files to the current user with the following command:
#   sudo chown -R $USER:$USER <DMS_output_score_folder>
#

# Source the configuration file
source Beltran_Lehner_2025_zero_shot_config.sh

# export DMS_index="0"
export DMS_output_score_folder="${DMS_output_score_folder_subs}/ESCOTT/"

# temporary folder for intermediate files generated by ESCOTT
# This folder will be removed after the execution
export TEMP_FOLDER="./escott_tmp/"  

# Docker image name
export DOCKER_IMAGE="/n/app/containers/shared/marks/prescott-docker_latest.sif"

# Remove temporary folder on exit
trap 'rm -rf $TEMP_FOLDER' EXIT

# Run the compute_fitness.py script in Singularity, disable looking for Rcpp and seqinr in the home folder, because these are installed in the container
singularity exec \
--no-home -B ${SCRIPT_DIR},$(dirname $(dirname $(dirname $(realpath $0)))):/root/ProteinGym,$DMS_reference_file_path_subs_pdb_range:/root/DMS_substitutions.csv,$DMS_data_folder_subs:/root/DMS_data,$DMS_MSA_data_folder:/root/MSA_data,$DMS_structure_folder:/root/structure_data,$DMS_output_score_folder:/root/output_scores \
-W /root/ProteinGym/scripts/scoring_DMS_zero_shot \
$DOCKER_IMAGE \
bash -c "
for i in {0..518}; do
    python3 -u ${SCRIPT_DIR}/escott/compute_fitness.py \
    --DMS_index=\$i \
    --DMS_reference_file_path=/root/DMS_substitutions.csv \
    --DMS_data_folder=/root/DMS_data \
    --MSA_folder=/root/MSA_data \
    --structure_data_folder=/root/structure_data \
    --output_scores_folder=/root/output_scores \
    --temp_folder=$TEMP_FOLDER \
    --nseqs=$NSEQS
done"

